repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0  # 使用最新版本
  hooks:
  - id: trailing-whitespace
    exclude: ^\.pre-commit-config\.yaml$
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: debug-statements
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --indent=2]
  - id: detect-private-key

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0  # 使用最新版本
  hooks:
  - id: flake8
    args: [--max-line-length=100, --exclude=.tox,venv]

- repo: https://github.com/psf/black
  rev: stable  # 使用最新稳定版本
  hooks:
  - id: black
    language_version: python3.9  # 确保与项目兼容的 Python 版本

- repo: https://github.com/asottile/blacken-docs
  rev: v1.13.0  # 使用最新版本
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==22.10.0]  # 使用与 black 兼容的版本

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1  # 使用最新版本
  hooks:
  - id: isort
    args: ['--profile', 'black']

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991  # 使用最新版本
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive, --show-error-codes]
    exclude: ^docs/

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.1  # 使用最新版本
  hooks:
  - id: autopep8
    args: [--in-place, --max-line-length=100, --ignore=E501]

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.13.5  # 使用最新版本
  hooks:
  - id: pylint
    args: [--rcfile=./pylintrc]
    exclude: ^docs/

- repo: local
  hooks:
  - id: safety
    name: Safety Check Dependencies for Vulnerabilities
    entry: poetry run safety check
    language: system
    types: [python]