# pip install -e .
# pip install pre-commit 
# pre-commit run --all-files
repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ['--line-length', '120']
-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ['--profile', 'black']

# - repo: https://github.com/PyCQA/flake8
#   rev: 6.0.0  # 使用最新版本
#   hooks:
#     - id: flake8
#       args: [--ignore=E203,E266,E501,W503]  # 自定义忽略规则