# receiver will use the perceptron model path to register the perceptron 
perceptron_model_path:
  - "wiseagent.receiver.perceptron.text_perceptron"
  - "wiseagent.receiver.perceptron.text_perceptron"