# receiver will use the perceptron model path to register the perceptron 
base_receiver_model_path: "wiseagent.receiver.base_receiver"
perceptron_module_path:
  - "wiseagent.receiver.perceptron.text_perceptron"
  - "wiseagent.receiver.perceptron.text_perceptron"

# Monitor Cofig
base_monitor_module_path: "wiseagent.monitor.monitor"
reporter_module_path:
  - "wiseagent.monitor.reporter.text_reporter"

# Life Schedule
life_module_path: "wiseagent.life.life"
life_schedule_module_path:
  - "wiseagent.life.life_scheduler.autostart_life_scheduler"
  - "wiseagent.life.life_scheduler.human_life_scheduler"
  - "wiseagent.life.life_scheduler.react_life_scheduler"

action_manager_module_path:"wiseagent.action.action_manager"
action_module_path:
  # plan action
  - "wiseagent.action.plan_action"
  # memory action
  - "wiseagent.action.memory_action"
