# Receiver
base_receiver_module_path: "wiseagent.receiver.base_receiver"
perceptron_module_path:
  - "wiseagent.receiver.perceptron.text_perceptron"

# Monitor Cofig
base_monitor_module_path: "wiseagent.monitor.monitor"
reporter_module_path:
  - "wiseagent.monitor.reporter.text_reporter"

# Life Schedule
life_manager_module_path: "wiseagent.life.life_manager"
life_scheduler_module_path:
  - "wiseagent.life.life_scheduler.autostart_life_scheduler"
  - "wiseagent.life.life_scheduler.human_life_scheduler"
  - "wiseagent.life.life_scheduler.react_life_scheduler"

# Action
action_manager_module_path: "wiseagent.action.action_manager"
action_module_path:
  # plan action
  - "wiseagent.action.plan_action.method_plan_acion"
  # memory action
  - "wiseagent.action.memory_action.knowledge_memory"
  - "wiseagent.action.memory_action.short_term_memory_action"
  - "wiseagent.action.memory_action.long_term_memory_action"
  # normal action
  - "wiseagent.action.normal_action.chat"
  - "wiseagent.action.normal_action.wechat"
  - "wiseagent.action.normal_action.arxiv"


# LLM
llm_manager_module_path: "wiseagent.llm.llm_manager"
llm_module_path:
  - "wiseagent.llm.deepseek"
  - "wiseagent.llm.baichuan"
