# receiver will use the perceptron model path to register the perceptron 
base_receiver_model_path: "wiseagent.receiver.base_receiver"
perceptron_module_path:
  - "wiseagent.receiver.perceptron.text_perceptron"
  - "wiseagent.receiver.perceptron.text_perceptron"

# Monitor Cofig
base_monitor_module_path: "wiseagent.monitor.monitor"
reporter_module_path:
  - "wiseagent.monitor.reporter.text_reporter"

# Life Schedule
life_schedule_path:
  - "wiseagent.life_manager.life_scheduler.autostart_life_scheduler"
  - "wiseagent.life_manager.life_scheduler.human_life_scheduler"
  - "wiseagent.life_manager.life_scheduler.react_life_scheduler"

